### PR TITLE
feat(app): introduce hpa

### PR DESCRIPTION
**Pull request by haveiss**
### Changes

- Add HPA capabilities to app charts to enable scaling for deployment by utilization. [Read more here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
- Non-breaking changes, disabled by default.

### CODE REVIEW

**Comment by mabdh** [comment]
@haveiss can you please add detailed description?

**Comment by haveiss** [comment]
> @haveiss can you please add detailed description?

added

**Comment by mabdh** [comment]
@haveiss is this still needed mas?

**Comment by haveiss** [comment]
> @haveiss is this still needed mas?

this is nice to have feature, any concerns if we merging it?

**Comment by mabdh** [comment]
@haveiss lets rebase to master and merge it mas?

**Review by mabdh — APPROVED** [review]

**Pull request merged**
